-- Migration 0026 · hotel_report_library
--
-- Persistent log of every institutional report generated by HotelVALORA.
-- Acts as the source of truth for `/library/favorites-list` and
-- `/library/favorites-map`: any report rendered for a canonical hotel
-- auto-upserts a row here so the library converts from a manually-seeded
-- marketplace into a live repository of generated reports.
--
-- 1:1 relation to `hotel_canonical` via `canonical_id` UNIQUE constraint.
-- Each canonical hotel has AT MOST one library entry · subsequent report
-- renders update the same row with the latest valuation snapshot.
-- (Future: when reports are versioned per scenario, add a separate
-- `hotel_report_library_version` audit table · this one tracks "latest".)
--
-- Public-read RLS · service-role writes only. The library is part of
-- the showcase layer · same posture as hotel_canonical / market /
-- submarket (migration 0025).

BEGIN;

-- ============================================================
-- 1 · Table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.hotel_report_library (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  canonical_id    uuid        NOT NULL UNIQUE
                              REFERENCES public.hotel_canonical(id) ON DELETE CASCADE,

  -- Snapshot fields · kept here for query/display performance · the
  -- canonical row remains the source of truth. These are denormalized
  -- on every UPSERT so the library page doesn't need to JOIN heavily.
  hotel_name      text        NOT NULL,
  city            text,
  market          text,
  submarket       text,
  chain_scale     text,
  star_rating     integer,
  total_rooms     integer,
  brand_family    text,
  lat             numeric(9, 6),
  lng             numeric(9, 6),

  -- Valuation block · from the cap-rate engine output at render time.
  -- Allow null for hotels that don't yet produce a valuation (e.g.
  -- engine returned null because category/market couldn't resolve).
  estimated_value_eur     numeric(18, 2),
  valuation_range_low_eur numeric(18, 2),
  valuation_range_high_eur numeric(18, 2),
  cap_rate_pct    numeric(6, 4),
  confidence_score integer CHECK (confidence_score BETWEEN 0 AND 100),
  per_key_eur     numeric(18, 2),
  per_sqm_eur     numeric(18, 2),
  gop_margin_pct  numeric(6, 4),

  -- Provenance + UX hooks
  report_url      text        NOT NULL,   -- /report/executive-summary?canonical_id=…
  report_status   text        NOT NULL DEFAULT 'generated',
                              -- 'generated' | 'partial' | 'failed' | 'archived'
  scenario_label  text,                   -- e.g. "Engine · base · CoStar submarket · Retiro"
  keys_from_heuristic boolean NOT NULL DEFAULT false,
  -- Tracks the chain_scale → keys heuristic fallback flag from the mapper
  -- so the library row also surfaces "heurístico" provenance.

  created_at      timestamptz NOT NULL DEFAULT NOW(),
  updated_at      timestamptz NOT NULL DEFAULT NOW(),
  last_rendered_at timestamptz NOT NULL DEFAULT NOW(),
  render_count    integer     NOT NULL DEFAULT 1
);

-- ============================================================
-- 2 · Indexes
-- ============================================================
CREATE INDEX IF NOT EXISTS hotel_report_library_canonical_idx
  ON public.hotel_report_library (canonical_id);
CREATE INDEX IF NOT EXISTS hotel_report_library_market_idx
  ON public.hotel_report_library (market, submarket);
CREATE INDEX IF NOT EXISTS hotel_report_library_chain_scale_idx
  ON public.hotel_report_library (chain_scale, star_rating);
CREATE INDEX IF NOT EXISTS hotel_report_library_last_rendered_idx
  ON public.hotel_report_library (last_rendered_at DESC);
CREATE INDEX IF NOT EXISTS hotel_report_library_geo_idx
  ON public.hotel_report_library (lat, lng)
  WHERE lat IS NOT NULL AND lng IS NOT NULL;

-- ============================================================
-- 3 · updated_at trigger
-- ============================================================
CREATE OR REPLACE FUNCTION public.tg_hotel_report_library_touch()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tg_hotel_report_library_touch ON public.hotel_report_library;
CREATE TRIGGER tg_hotel_report_library_touch
  BEFORE UPDATE ON public.hotel_report_library
  FOR EACH ROW EXECUTE FUNCTION public.tg_hotel_report_library_touch();

-- ============================================================
-- 4 · RLS · public-read · service-role writes (anon cannot insert)
-- ============================================================
ALTER TABLE public.hotel_report_library ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "hotel_report_library_read_public" ON public.hotel_report_library;
CREATE POLICY "hotel_report_library_read_public"
  ON public.hotel_report_library
  FOR SELECT TO public
  USING (report_status <> 'archived');

-- INSERT/UPDATE/DELETE: only service-role (bypasses RLS implicitly).
-- No explicit write policy · anon + authenticated cannot mutate.

-- ============================================================
-- 5 · Sanity probe
-- ============================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'hotel_report_library'
      AND policyname = 'hotel_report_library_read_public'
  ) THEN
    RAISE EXCEPTION 'Migration 0026 incomplete · read policy missing';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'hotel_report_library'
      AND column_name = 'canonical_id'
  ) THEN
    RAISE EXCEPTION 'Migration 0026 incomplete · canonical_id column missing';
  END IF;
END $$;

COMMIT;
