-- ============================================================================
-- Migration 0035 · pnl_template + pnl_template_override (FASE 1 of Supabase migration)
-- ============================================================================
-- Applied via Supabase MCP on 2026-05-28 (project twebgqutuqgonabvhzjk).
--
-- Single source of truth for USALI percentages, keyed by
-- (country × market × submarket × class × segmentation_type).
-- Replaces the hardcoded PNL_FORECAST_5Y array in
-- apps/web/src/lib/admin/financials/defaults.ts and removes the
-- localStorage-only persistence of operator edits (institutional debt).
--
-- Canonical naming: keys are CoStar English (e.g. "Madrid Centre", "Upper
-- Upscale") · display translation lives in the UI layer (FASE 3).
--
-- Methodology decisions baked in (see VALUATION_METHODOLOGY.md):
--   · HotelVALORA EBITDA pre-alquiler: it_telecom_pct and rent_pct are
--     stored for CoStar parity but EXCLUDED from the engine EBITDA calc.
--   · derived_mvp_rule data_source: apartahotel/hostel rows generated by
--     the importer (FASE 2) using documented sector rules
--     (mgmt_fee 20% apartahotel · 12% hostel).
--
-- Scalability notes:
--   · costar_national (not costar_national_ES) so the enum is geo-agnostic.
--     The country lives in the country column.
--   · NULLS NOT DISTINCT on the composite key (PG15+) so country-only
--     placeholder rows for pending countries don't collapse.
--   · View runs with security_invoker=false (default) so anon report
--     rendering sees merged effective values, while pnl_template_override
--     itself stays inaccessible to anon (no RLS policies grant read).
-- ============================================================================

-- ── Enums ──────────────────────────────────────────────────────────────────

create type public.pnl_data_source as enum (
  'costar_real',                -- live CoStar data for this exact combination
  'costar_submarket_aggregate', -- synthesized from submarket-level CoStar median
  'costar_national',            -- synthesized from country-level CoStar median (country in the country column)
  'hardcoded_default',          -- methodology-firmed defaults (Madrid Centre Upper Upscale baseline)
  'derived_mvp_rule',           -- derived using documented sector rules (apartahotel/hostel)
  'pending_costar'              -- placeholder · no data loaded yet
);

create type public.pnl_segmentation_type as enum ('hotel', 'apartahotel', 'hostel');

-- ── Table: pnl_template (canonical source · written by importer) ───────────

create table public.pnl_template (
  id uuid primary key default gen_random_uuid(),

  country char(2) not null,
  market text,
  submarket text,
  class text,
  segmentation_type public.pnl_segmentation_type,

  rooms_revenue_pct numeric(5,2),
  fb_food_pct numeric(5,2),
  fb_beverage_pct numeric(5,2),
  meeting_events_pct numeric(5,2),
  spa_wellness_pct numeric(5,2),
  parking_other_pct numeric(5,2),

  expenses_rooms_pct numeric(5,2),
  expenses_fb_pct numeric(5,2),
  other_departments_pct numeric(5,2),

  admin_general_pct numeric(5,2),
  it_telecom_pct numeric(5,2),
  sales_marketing_pct numeric(5,2),
  operations_maintenance_pct numeric(5,2),
  utilities_pct numeric(5,2),

  gop_pct numeric(5,2),
  management_fees_pct numeric(5,2),
  rent_pct numeric(5,2),
  property_taxes_pct numeric(5,2),
  insurance_pct numeric(5,2),
  ebitda_pct numeric(5,2),
  staff_cost_memo_pct numeric(5,2),

  data_source public.pnl_data_source not null,
  last_imported_at timestamptz not null default now(),
  imported_from text,
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint pnl_template_uk
    unique nulls not distinct (country, market, submarket, class, segmentation_type)
);

comment on table public.pnl_template is
  'USALI P&L percentages keyed by (country × market × submarket × class × segmentation_type). Canonical source of truth · written by services/costar/scripts/build_financials_master.py from COSTAR_MASTER_FINANCIALS.xlsx. Read by both /user/admin/financials panel and the report P&L engine. CoStar-canonical English keys; display translation in apps/web/src/lib/admin/financials/pnl-i18n.ts.';

comment on column public.pnl_template.it_telecom_pct is
  'EXCLUDED from the HotelVALORA EBITDA calculation. Stored for CoStar parity and informational display. See VALUATION_METHODOLOGY.md annex "Modelo HotelVALORA de EBITDA".';

comment on column public.pnl_template.rent_pct is
  'EXCLUDED from the HotelVALORA EBITDA calculation. Stored for CoStar parity and informational display. See VALUATION_METHODOLOGY.md annex "Modelo HotelVALORA de EBITDA".';

comment on column public.pnl_template.ebitda_pct is
  'CoStar EBITDA percentage (informational). The HotelVALORA-computed EBITDA differs: GOP - management_fees - property_taxes - insurance (no IT/Telecom · no Rent). See methodology annex.';

create index idx_pnl_template_geo on public.pnl_template (country, market, submarket);
create index idx_pnl_template_source on public.pnl_template (data_source);
create index idx_pnl_template_class_seg on public.pnl_template (class, segmentation_type);

alter table public.pnl_template enable row level security;

create policy "pnl_template public read" on public.pnl_template
  for select to anon, authenticated using (true);

-- Writes restricted to service_role (importer + server actions). service_role
-- bypasses RLS by default, so no explicit policy is needed for it.

-- ── Table: pnl_template_override (operator editorial · written via server action) ──

create table public.pnl_template_override (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.pnl_template(id) on delete cascade,

  line_item text not null,
  override_value numeric(5,2) not null,

  operator_email text not null,
  operator_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint pnl_override_uk unique (template_id, line_item),
  constraint pnl_override_line_item_known check (line_item in (
    'rooms_revenue_pct','fb_food_pct','fb_beverage_pct','meeting_events_pct',
    'spa_wellness_pct','parking_other_pct',
    'expenses_rooms_pct','expenses_fb_pct','other_departments_pct',
    'admin_general_pct','it_telecom_pct','sales_marketing_pct',
    'operations_maintenance_pct','utilities_pct',
    'gop_pct','management_fees_pct','rent_pct','property_taxes_pct',
    'insurance_pct','ebitda_pct','staff_cost_memo_pct'
  ))
);

comment on table public.pnl_template_override is
  'Operator-curated edits layered on top of pnl_template. Written via server action gated by requireOperator() · the panel never connects directly. NOT touched by the importer when refreshing pnl_template from CoStar/Excel so operator corrections survive data refreshes. View pnl_template_effective merges this with the template via COALESCE per line.';

create index idx_pnl_override_template on public.pnl_template_override (template_id);
create index idx_pnl_override_operator on public.pnl_template_override (operator_email);

alter table public.pnl_template_override enable row level security;
-- NO policies = no anon/authenticated access. service_role only (bypasses RLS by default).

-- ── updated_at trigger ─────────────────────────────────────────────────────

create or replace function public.tg_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger pnl_template_set_updated_at
  before update on public.pnl_template
  for each row execute function public.tg_set_updated_at();

create trigger pnl_template_override_set_updated_at
  before update on public.pnl_template_override
  for each row execute function public.tg_set_updated_at();

-- ── View: pnl_template_effective (template merged with overrides) ──────────

create or replace view public.pnl_template_effective
with (security_invoker = false) as
select
  t.id,
  t.country,
  t.market,
  t.submarket,
  t.class,
  t.segmentation_type,
  t.data_source,
  t.last_imported_at,
  t.imported_from,
  t.notes,
  t.created_at,
  t.updated_at,

  coalesce(o.rooms_revenue_pct,  t.rooms_revenue_pct)  as rooms_revenue_pct,
  coalesce(o.fb_food_pct,        t.fb_food_pct)        as fb_food_pct,
  coalesce(o.fb_beverage_pct,    t.fb_beverage_pct)    as fb_beverage_pct,
  coalesce(o.meeting_events_pct, t.meeting_events_pct) as meeting_events_pct,
  coalesce(o.spa_wellness_pct,   t.spa_wellness_pct)   as spa_wellness_pct,
  coalesce(o.parking_other_pct,  t.parking_other_pct)  as parking_other_pct,

  coalesce(o.expenses_rooms_pct,    t.expenses_rooms_pct)    as expenses_rooms_pct,
  coalesce(o.expenses_fb_pct,       t.expenses_fb_pct)       as expenses_fb_pct,
  coalesce(o.other_departments_pct, t.other_departments_pct) as other_departments_pct,

  coalesce(o.admin_general_pct,          t.admin_general_pct)          as admin_general_pct,
  coalesce(o.it_telecom_pct,             t.it_telecom_pct)             as it_telecom_pct,
  coalesce(o.sales_marketing_pct,        t.sales_marketing_pct)        as sales_marketing_pct,
  coalesce(o.operations_maintenance_pct, t.operations_maintenance_pct) as operations_maintenance_pct,
  coalesce(o.utilities_pct,              t.utilities_pct)              as utilities_pct,

  coalesce(o.gop_pct,             t.gop_pct)             as gop_pct,
  coalesce(o.management_fees_pct, t.management_fees_pct) as management_fees_pct,
  coalesce(o.rent_pct,            t.rent_pct)            as rent_pct,
  coalesce(o.property_taxes_pct,  t.property_taxes_pct)  as property_taxes_pct,
  coalesce(o.insurance_pct,       t.insurance_pct)       as insurance_pct,
  coalesce(o.ebitda_pct,          t.ebitda_pct)          as ebitda_pct,
  coalesce(o.staff_cost_memo_pct, t.staff_cost_memo_pct) as staff_cost_memo_pct,

  o.overridden_lines

from public.pnl_template t
left join lateral (
  select
    max(override_value) filter (where line_item = 'rooms_revenue_pct')          as rooms_revenue_pct,
    max(override_value) filter (where line_item = 'fb_food_pct')                as fb_food_pct,
    max(override_value) filter (where line_item = 'fb_beverage_pct')            as fb_beverage_pct,
    max(override_value) filter (where line_item = 'meeting_events_pct')         as meeting_events_pct,
    max(override_value) filter (where line_item = 'spa_wellness_pct')           as spa_wellness_pct,
    max(override_value) filter (where line_item = 'parking_other_pct')          as parking_other_pct,
    max(override_value) filter (where line_item = 'expenses_rooms_pct')         as expenses_rooms_pct,
    max(override_value) filter (where line_item = 'expenses_fb_pct')            as expenses_fb_pct,
    max(override_value) filter (where line_item = 'other_departments_pct')      as other_departments_pct,
    max(override_value) filter (where line_item = 'admin_general_pct')          as admin_general_pct,
    max(override_value) filter (where line_item = 'it_telecom_pct')             as it_telecom_pct,
    max(override_value) filter (where line_item = 'sales_marketing_pct')        as sales_marketing_pct,
    max(override_value) filter (where line_item = 'operations_maintenance_pct') as operations_maintenance_pct,
    max(override_value) filter (where line_item = 'utilities_pct')              as utilities_pct,
    max(override_value) filter (where line_item = 'gop_pct')                    as gop_pct,
    max(override_value) filter (where line_item = 'management_fees_pct')        as management_fees_pct,
    max(override_value) filter (where line_item = 'rent_pct')                   as rent_pct,
    max(override_value) filter (where line_item = 'property_taxes_pct')         as property_taxes_pct,
    max(override_value) filter (where line_item = 'insurance_pct')              as insurance_pct,
    max(override_value) filter (where line_item = 'ebitda_pct')                 as ebitda_pct,
    max(override_value) filter (where line_item = 'staff_cost_memo_pct')        as staff_cost_memo_pct,
    coalesce(array_agg(line_item order by line_item), array[]::text[])          as overridden_lines
  from public.pnl_template_override
  where template_id = t.id
) o on true;

comment on view public.pnl_template_effective is
  'Per-template effective USALI percentages with operator overrides merged (COALESCE override over template, per line). Used by both /user/admin/financials panel display and the report P&L engine. overridden_lines[] surfaces which lines carry an operator override (audit transparency). View runs as definer (security_invoker=false) so the anon report path sees merged values while pnl_template_override itself stays inaccessible to anon.';
