// Market Dynamics data contract.
//
// 4-axis filter state (scope × class × KPI × horizon) drives 6 chart "angles"
// of the same KPI. Designed to be replaced by the future market intelligence
// service — every value is generated by `getDynamicsCharts(filters)` so the
// UI layer never reaches into raw arrays.

// ── Filter axes ─────────────────────────────────────────────────────────────

export type DynamicsScope =
  | "country"
  | "market"
  | "submarket"
  | "compset"
  | "forecast";

export type DynamicsClass =
  | "general"
  | "luxury"
  | "upper-upscale"
  | "upscale"
  | "midscale"
  | "basic";

export type DynamicsKpi =
  | "occupancy"
  | "adr"
  | "revpar"
  | "supply-rn"
  | "demand-rn";

export type DynamicsHorizon = "12m" | "3y" | "5y" | "10y";

export interface DynamicsFilterState {
  scope: DynamicsScope;
  class: DynamicsClass;
  kpi: DynamicsKpi;
  horizon: DynamicsHorizon;
}

export interface DynamicsFilterOption<T extends string = string> {
  id: T;
  label: string;
}

export const SCOPE_OPTIONS: DynamicsFilterOption<DynamicsScope>[] = [
  { id: "country", label: "Country" },
  { id: "market", label: "Market" },
  { id: "submarket", label: "Submarket" },
  { id: "compset", label: "CompSet" },
  { id: "forecast", label: "Forecast" },
];

export const CLASS_OPTIONS: DynamicsFilterOption<DynamicsClass>[] = [
  { id: "general", label: "General" },
  { id: "luxury", label: "Luxury" },
  { id: "upper-upscale", label: "Upper Upscale" },
  { id: "upscale", label: "Upscale" },
  { id: "midscale", label: "Midscale" },
  { id: "basic", label: "Basic" },
];

export const KPI_OPTIONS: DynamicsFilterOption<DynamicsKpi>[] = [
  { id: "occupancy", label: "Occupancy" },
  { id: "adr", label: "ADR" },
  { id: "revpar", label: "RevPAR" },
  { id: "supply-rn", label: "Supply RN" },
  { id: "demand-rn", label: "Demand RN" },
];

export const HORIZON_OPTIONS: DynamicsFilterOption<DynamicsHorizon>[] = [
  { id: "12m", label: "12M" },
  { id: "3y", label: "3Y" },
  { id: "5y", label: "5Y" },
  { id: "10y", label: "10Y" },
];

export const DEFAULT_FILTERS: DynamicsFilterState = {
  scope: "market",
  class: "general",
  kpi: "revpar",
  horizon: "5y",
};

// ── Lookup tables ───────────────────────────────────────────────────────────

const KPI_META: Record<
  DynamicsKpi,
  { full: string; short: string; unit: string }
> = {
  occupancy: { full: "Occupancy", short: "OCC", unit: "%" },
  adr: { full: "ADR", short: "ADR", unit: "€" },
  revpar: { full: "RevPAR", short: "RevPAR", unit: "€" },
  "supply-rn": { full: "Supply RN", short: "Supply", unit: "RN" },
  "demand-rn": { full: "Demand RN", short: "Demand", unit: "RN" },
};

const SCOPE_TITLES: Record<DynamicsScope, string> = {
  country: "España",
  market: "Madrid",
  submarket: "Madrid Centro",
  compset: "CompSet",
  forecast: "Forecast 5Y",
};

const HORIZON_LABELS: Record<DynamicsHorizon, string[]> = {
  "12m": ["Jan", "Mar", "May", "Jul", "Sep", "Nov"],
  "3y": ["2023", "Q3", "2024", "Q3", "2025", "Q3"],
  "5y": ["2021", "2022", "2023", "2024", "2025"],
  "10y": ["2016", "2018", "2020", "2022", "2024", "2026"],
};

const HORIZON_FORECAST_LABELS: Record<DynamicsHorizon, [string, string]> = {
  "12m": ["+3M", "+6M"],
  "3y": ["F+1", "F+2"],
  "5y": ["F+1", "F+2"],
  "10y": ["2028", "2030"],
};

// ── Chart shape ─────────────────────────────────────────────────────────────

export type DynamicsAngle =
  | "historical"
  | "forecast"
  | "yoy"
  | "vs-compset"
  | "segment"
  | "distribution";

export interface DynamicsSeries {
  /** Y values in 0..40 viewBox space */
  values: number[];
  /**
   * Index in `xLabels` where the first value lands. Lets a forecast series
   * start at the last historical x position without overlapping the prior path.
   */
  startIndex?: number;
  style: "solid" | "dashed";
  /** CSS hex colour */
  color: string;
  /** Optional legend label */
  label?: string;
}

export interface DynamicsChart {
  id: DynamicsAngle;
  /** Card title (e.g. "Histórico") */
  title: string;
  /** Right-aligned pill (KPI short, segment, "Forecast +12M", …) */
  badge?: string;
  /** Y-axis unit (rendered top-right, small) */
  unit?: string;
  /** X labels */
  xLabels: string[];
  /** Stacked series — first one drawn on top */
  series: DynamicsSeries[];
}

// ── Deterministic mock generator ────────────────────────────────────────────

/**
 * Linear-congruential pseudo-random — deterministic so the same filter combo
 * always renders the same series. Returns an integer 0..maxInt.
 */
function nextSeed(s: number): number {
  return (s * 9301 + 49297) % 233280;
}

/** Hash filter combo into a stable seed. */
function hashFilters(f: DynamicsFilterState): number {
  const s = `${f.scope}:${f.class}:${f.kpi}:${f.horizon}`;
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = (h << 5) - h + s.charCodeAt(i);
    h |= 0;
  }
  return Math.abs(h) || 1;
}

/**
 * Generate `count` Y values around `base` with a `drift` linear trend and
 * `amplitude` noise. Always clamped to 4..36 so the line never touches the
 * card edges.
 */
function shape(
  seed: number,
  count: number,
  base: number,
  amplitude: number,
  drift: number,
): number[] {
  const result: number[] = [];
  let s = seed;
  for (let i = 0; i < count; i++) {
    s = nextSeed(s);
    const noise = s / 233280 - 0.5;
    const t = count <= 1 ? 0 : i / (count - 1);
    const value = base + drift * t + amplitude * noise * 2;
    result.push(Math.max(4, Math.min(36, value)));
  }
  return result;
}

/** Public API — returns 6 charts ready to render for the given filter combo. */
export function getDynamicsCharts(
  filters: DynamicsFilterState,
): DynamicsChart[] {
  const seed = hashFilters(filters);
  const xLabels = HORIZON_LABELS[filters.horizon];
  const points = xLabels.length;
  const kpi = KPI_META[filters.kpi];
  const scope = SCOPE_TITLES[filters.scope];
  const klass = CLASS_OPTIONS.find((o) => o.id === filters.class)?.label ?? "—";

  // Base series shared across the angles that compare against historical
  const historical = shape(seed + 1, points, 22, 6, 6); // upward trend
  const compset = shape(seed + 13, points, 24, 4, 4);
  const segmentAvg = shape(seed + 29, points, 18, 5, 7);
  const yoy = shape(seed + 41, points, 22, 12, 0); // oscillating
  const distMedian = shape(seed + 53, points, 22, 4, 0); // tight band

  // Forecast tail — 2 future points starting at last historical Y
  const last = historical[historical.length - 1];
  const tailRaw = shape(seed + 71, 2, last + 1, 3, 2);
  const forecastSeries: number[] = [last, ...tailRaw];
  const forecastXLabels = [
    ...xLabels,
    ...HORIZON_FORECAST_LABELS[filters.horizon],
  ];

  return [
    {
      id: "historical",
      title: "Histórico",
      badge: kpi.short,
      unit: kpi.unit,
      xLabels,
      series: [
        {
          style: "solid",
          color: "#065f46",
          values: historical,
          label: scope,
        },
      ],
    },
    {
      id: "forecast",
      title: "Forecast",
      badge: `${kpi.short} +24M`,
      unit: kpi.unit,
      xLabels: forecastXLabels,
      series: [
        {
          style: "solid",
          color: "#065f46",
          values: historical,
          label: "Real",
        },
        {
          style: "dashed",
          color: "#10b981",
          values: forecastSeries,
          startIndex: points - 1,
          label: "Forecast",
        },
      ],
    },
    {
      id: "yoy",
      title: "YoY %",
      badge: "Var. anual",
      unit: "%",
      xLabels,
      series: [
        {
          style: "solid",
          color: "#0f766e",
          values: yoy,
          label: "YoY",
        },
      ],
    },
    {
      id: "vs-compset",
      title: "vs CompSet",
      badge: scope,
      unit: kpi.unit,
      xLabels,
      series: [
        {
          style: "solid",
          color: "#065f46",
          values: historical,
          label: scope,
        },
        {
          style: "dashed",
          color: "#94a3b8",
          values: compset,
          label: "CompSet",
        },
      ],
    },
    {
      id: "segment",
      title: "Segmento",
      badge: klass,
      unit: kpi.unit,
      xLabels,
      series: [
        {
          style: "solid",
          color: "#065f46",
          values: historical,
          label: "Selección",
        },
        {
          style: "dashed",
          color: "#94a3b8",
          values: segmentAvg,
          label: "Segment avg",
        },
      ],
    },
    {
      id: "distribution",
      title: "Distribución",
      badge: "Mediana",
      unit: kpi.unit,
      xLabels,
      series: [
        {
          style: "solid",
          color: "#0f766e",
          values: distMedian,
          label: "P50",
        },
      ],
    },
  ];
}
