import type {
  CategoryBreakdownRow,
  EntityMentionsRow,
  ExtractedDeal,
  ExtractedProject,
  IntelligenceTerminalData,
  NewsItem,
  RelevanceAlert,
  SourceCoverageRow,
  VolumeKpi,
} from "./types";

/**
 * Mock data for the Market Intelligence Terminal.
 *
 * Source-of-shape: migration 0006_hospitality_intelligence_schema.sql.
 * Realistic European hospitality activity drawn from the 30-day window
 * (2026-04-13 → 2026-05-12). All currency values in EUR.
 *
 * Phase 3 swaps this whole module for a server-side fetch:
 *   - SELECT ... FROM market_news WHERE published_at >= now() - interval '7 days'
 *   - left-join hotel_transactions / hotel_projects
 *   - left-join news_entities, news_tags
 *   - rollup by category / source / entity
 * The shape returned to components stays identical.
 */

// ── Volume KPI strip ────────────────────────────────────────────────────────

export const MOCK_VOLUME_KPIS: VolumeKpi[] = [
  {
    id: "today",
    label: "Articles Today",
    value: "78",
    subline: "↑ vs 7d mean of 71",
    trend: "+9.9%",
    signal: "ok",
  },
  {
    id: "wow",
    label: "Articles · 7 Days",
    value: "542",
    subline: "8 sources active · 561 last week",
    trend: "−3.4%",
    signal: "neutral",
  },
  {
    id: "transactions",
    label: "Transactions Detected · 7d",
    value: "14",
    subline: "9 acquisitions · 3 sales · 2 JV",
    trend: "+27%",
    signal: "ok",
  },
  {
    id: "projects",
    label: "Pipeline Projects · 7d",
    value: "11",
    subline: "5 development · 4 rebranding · 2 conversion",
    trend: "stable",
    signal: "ok",
  },
  {
    id: "transaction_volume",
    label: "Disclosed Volume · 7d",
    value: "€1.42B",
    subline: "across 9 disclosed deals · €/key range 215k–410k",
    trend: "+18%",
    signal: "ok",
  },
  {
    id: "session_health",
    label: "Authenticated Sources",
    value: "0 / 2",
    subline: "Hosteltur · Alimarket pending credentials",
    signal: "warn",
  },
];

// ── Recent news items ───────────────────────────────────────────────────────

export const MOCK_RECENT_NEWS: NewsItem[] = [
  {
    id: "mn-001",
    sourceSlug: "hospitalitynet",
    sourceName: "HospitalityNet",
    title: "Brookfield acquires 12-property portfolio from Banco Santander for €820M",
    summary: "Brookfield Asset Management has completed the acquisition of a 12-hotel portfolio across Madrid, Barcelona, and Mallorca from Banco Santander's real estate arm. The 2,140-room collection — operated under Iberostar and Barceló brands — closed at an implied €383k/key.",
    url: "https://www.hospitalitynet.org/news/4140123-brookfield-portfolio-spain.html",
    publishedAt: "2026-05-12T08:14:00Z",
    country: "ES",
    market: "Spain · Multi-asset",
    city: "Madrid",
    category: "acquisition",
    hotelSegment: "upper_upscale",
    brandAffiliation: "branded",
    language: "en",
    tags: ["portfolio", "spain", "brookfield", "santander", "iberostar", "barcelo"],
    entities: [
      { kind: "investor", id: "brookfield", rawMention: "Brookfield Asset Management", role: "buyer", confidence: 0.95 },
      { kind: "investor", id: "santander-re", rawMention: "Banco Santander", role: "seller", confidence: 0.92 },
      { kind: "operator", id: "iberostar", rawMention: "Iberostar", role: "operator", confidence: 0.90 },
      { kind: "operator", id: "barcelo", rawMention: "Barceló", role: "operator", confidence: 0.88 },
    ],
    relevanceScore: 96,
    relevanceBand: "critical",
  },
  {
    id: "mn-002",
    sourceSlug: "expansion",
    sourceName: "Expansión",
    title: "Blackstone refinancia 1.200 millones en cartera hotelera europea con Goldman Sachs",
    summary: "Blackstone ha cerrado una refinanciación de €1.200M de su cartera hotelera europea con Goldman Sachs como bookrunner. La operación cubre 38 activos en España, Italia y Portugal con un LTV objetivo de 55%.",
    url: "https://www.expansion.com/empresas/inmobiliario/2026/05/11/blackstone-refinanciacion.html",
    publishedAt: "2026-05-11T15:22:00Z",
    country: "ES",
    market: "Europe · Portfolio",
    city: null,
    category: "refinancing",
    hotelSegment: "upper_upscale",
    brandAffiliation: "branded",
    language: "es",
    tags: ["refinancing", "blackstone", "goldman", "portfolio", "europe"],
    entities: [
      { kind: "investor", id: "blackstone", rawMention: "Blackstone", role: "investor", confidence: 0.97 },
      { kind: "investor", id: "goldman", rawMention: "Goldman Sachs", role: "lender", confidence: 0.94 },
    ],
    relevanceScore: 91,
    relevanceBand: "critical",
  },
  {
    id: "mn-003",
    sourceSlug: "skift-hospitality",
    sourceName: "Skift Hospitality",
    title: "Marriott to open 28 new EDITION-branded hotels in EMEA by 2028",
    summary: "Marriott International announced a pipeline of 28 EDITION-branded properties across EMEA, with first openings targeted for Madrid (2027), Lisbon (2027), and Athens (2028). The pipeline lifts EDITION's EMEA footprint by 175%.",
    url: "https://skift.com/2026/05/11/marriott-edition-emea-pipeline/",
    publishedAt: "2026-05-11T11:03:00Z",
    country: null,
    market: "EMEA · Pipeline",
    city: null,
    category: "pipeline_announcement",
    hotelSegment: "luxury",
    brandAffiliation: "branded",
    language: "en",
    tags: ["pipeline", "marriott", "edition", "luxury", "emea"],
    entities: [
      { kind: "operator", id: "marriott", rawMention: "Marriott International", role: "operator", confidence: 0.98 },
    ],
    relevanceScore: 84,
    relevanceBand: "high",
  },
  {
    id: "mn-004",
    sourceSlug: "hospitalitynet",
    sourceName: "HospitalityNet",
    title: "Accor and CDC create €500M JV for European luxury repositioning",
    summary: "Accor and Caisse des Dépôts have formed a €500M joint venture targeting luxury hotel repositioning across France, Spain, and Italy. Initial seed: three Parisian assets currently operated under Sofitel and one Barcelona property.",
    url: "https://www.hospitalitynet.org/news/4140087-accor-cdc-jv.html",
    publishedAt: "2026-05-10T09:40:00Z",
    country: "FR",
    market: "Europe · Luxury",
    city: "Paris",
    category: "joint_venture",
    hotelSegment: "luxury",
    brandAffiliation: "branded",
    language: "en",
    tags: ["jv", "accor", "cdc", "luxury", "repositioning"],
    entities: [
      { kind: "operator", id: "accor", rawMention: "Accor", role: "operator", confidence: 0.97 },
      { kind: "investor", id: "cdc", rawMention: "Caisse des Dépôts", role: "partner", confidence: 0.93 },
    ],
    relevanceScore: 88,
    relevanceBand: "high",
  },
  {
    id: "mn-005",
    sourceSlug: "hvs",
    sourceName: "HVS",
    title: "Madrid hotel transactions volume up 34% YoY through Q1 2026",
    summary: "HVS Madrid's Q1 2026 brief shows transaction volume reached €1.86B across 23 deals — up 34% YoY. Average €/key climbed to €295k for upper-upscale, €410k for luxury. Foreign capital represented 78% of acquirers.",
    url: "https://www.hvs.com/article/9876/madrid-q1-2026-transactions/",
    publishedAt: "2026-05-09T14:00:00Z",
    country: "ES",
    market: "Madrid",
    city: "Madrid",
    category: "investment",
    hotelSegment: "upper_upscale",
    brandAffiliation: "unknown",
    language: "en",
    tags: ["madrid", "transactions", "q1-2026", "research", "europrice"],
    entities: [],
    relevanceScore: 78,
    relevanceBand: "high",
  },
  {
    id: "mn-006",
    sourceSlug: "expansion",
    sourceName: "Expansión",
    title: "Meliá completa la venta del Hotel Princesa Plaza Madrid a Stoneweg por €145M",
    summary: "Meliá Hotels International ha cerrado la venta del Hotel Princesa Plaza Madrid (406 habitaciones) al fondo suizo Stoneweg por €145M. El acuerdo incluye un contrato de gestión a 25 años bajo la marca Meliá Collection.",
    url: "https://www.expansion.com/empresas/turismo/2026/05/08/melia-princesa-stoneweg.html",
    publishedAt: "2026-05-08T16:30:00Z",
    country: "ES",
    market: "Madrid Centro",
    city: "Madrid",
    category: "sale",
    hotelSegment: "upper_upscale",
    brandAffiliation: "branded",
    language: "es",
    tags: ["sale", "madrid", "melia", "stoneweg", "sale-and-manage-back"],
    entities: [
      { kind: "operator", id: "melia", rawMention: "Meliá Hotels International", role: "seller", confidence: 0.96 },
      { kind: "investor", id: "stoneweg", rawMention: "Stoneweg", role: "buyer", confidence: 0.94 },
    ],
    relevanceScore: 92,
    relevanceBand: "critical",
  },
  {
    id: "mn-007",
    sourceSlug: "reuters-hospitality",
    sourceName: "Reuters Hospitality",
    title: "KKR-backed Mint House files for restructuring, eyes flex-living conversion",
    summary: "Mint House, the flexible-stay operator backed by KKR, has filed for Chapter 11 protection in the U.S. while announcing plans to convert four Spanish assets to a long-stay flex-living format.",
    url: "https://www.reuters.com/business/lifestyle/mint-house-restructuring-2026-05-08/",
    publishedAt: "2026-05-08T13:18:00Z",
    country: "ES",
    market: "Spain · Multi-asset",
    city: null,
    category: "distress",
    hotelSegment: "lifestyle",
    brandAffiliation: "branded",
    language: "en",
    tags: ["distress", "kkr", "mint-house", "flex-living", "conversion"],
    entities: [
      { kind: "investor", id: "kkr", rawMention: "KKR", role: "investor", confidence: 0.96 },
      { kind: "operator", id: "mint-house", rawMention: "Mint House", role: "operator", confidence: 0.92 },
    ],
    relevanceScore: 89,
    relevanceBand: "high",
  },
  {
    id: "mn-008",
    sourceSlug: "skift-hospitality",
    sourceName: "Skift Hospitality",
    title: "Six Senses to debut in Mallorca with 120-key luxury resort opening 2027",
    summary: "IHG-owned Six Senses confirmed its first Mallorca property — a 120-key luxury resort in Cap de Formentor — with opening targeted Q3 2027. Developer Inversiones Mallorquinas is leading the €185M development.",
    url: "https://skift.com/2026/05/07/six-senses-mallorca-formentor/",
    publishedAt: "2026-05-07T10:45:00Z",
    country: "ES",
    market: "Mallorca",
    city: "Cap de Formentor",
    category: "development",
    hotelSegment: "luxury",
    brandAffiliation: "branded",
    language: "en",
    tags: ["development", "six-senses", "ihg", "mallorca", "luxury"],
    entities: [
      { kind: "operator", id: "six-senses", rawMention: "Six Senses", role: "operator", confidence: 0.97 },
      { kind: "investor", id: "inversiones-mallorquinas", rawMention: "Inversiones Mallorquinas", role: "developer", confidence: 0.87 },
    ],
    relevanceScore: 81,
    relevanceBand: "high",
  },
];

// ── Extracted deals ─────────────────────────────────────────────────────────

export const MOCK_EXTRACTED_DEALS: ExtractedDeal[] = [
  {
    id: "tx-001",
    newsId: "mn-001",
    newsTitle: "Brookfield acquires 12-property portfolio from Banco Santander for €820M",
    sourceSlug: "hospitalitynet",
    category: "acquisition",
    assetName: "Santander Spain Portfolio (12 assets)",
    country: "ES",
    city: "Madrid · Barcelona · Mallorca",
    market: "Spain · Multi-asset",
    rooms: 2140,
    priceEur: 820_000_000,
    pricePerKeyEur: 383_178,
    capRate: null,
    closedAt: "2026-05-12",
    announcedAt: "2026-05-12",
    buyer: "Brookfield Asset Management",
    seller: "Banco Santander",
    operator: "Iberostar · Barceló",
    brand: "Iberostar · Barceló",
    advisorBuy: "JLL",
    advisorSell: "CBRE",
    sourceUrl: "https://www.hospitalitynet.org/news/4140123-brookfield-portfolio-spain.html",
    notes: "Portfolio sale · cross-brand operator continuity in place.",
  },
  {
    id: "tx-002",
    newsId: "mn-006",
    newsTitle: "Meliá completa la venta del Hotel Princesa Plaza Madrid a Stoneweg por €145M",
    sourceSlug: "expansion",
    category: "sale",
    assetName: "Hotel Princesa Plaza Madrid",
    country: "ES",
    city: "Madrid",
    market: "Madrid Centro",
    rooms: 406,
    priceEur: 145_000_000,
    pricePerKeyEur: 357_142,
    capRate: 5.2,
    closedAt: "2026-05-08",
    announcedAt: "2026-05-08",
    buyer: "Stoneweg",
    seller: "Meliá Hotels International",
    operator: "Meliá Collection",
    brand: "Meliá Collection",
    advisorBuy: "Cushman & Wakefield",
    advisorSell: "Colliers",
    sourceUrl: "https://www.expansion.com/empresas/turismo/2026/05/08/melia-princesa-stoneweg.html",
    notes: "Sale-and-manage-back · 25y management contract retained.",
  },
  {
    id: "tx-003",
    newsId: "mn-002",
    newsTitle: "Blackstone refinancia 1.200 millones en cartera hotelera europea con Goldman Sachs",
    sourceSlug: "expansion",
    category: "refinancing",
    assetName: "Blackstone European Hotels Portfolio (38 assets)",
    country: null,
    city: null,
    market: "Europe · Portfolio",
    rooms: null,
    priceEur: 1_200_000_000,
    pricePerKeyEur: null,
    capRate: null,
    closedAt: "2026-05-11",
    announcedAt: "2026-05-11",
    buyer: null,
    seller: null,
    operator: null,
    brand: null,
    advisorBuy: null,
    advisorSell: "Goldman Sachs (bookrunner)",
    sourceUrl: "https://www.expansion.com/empresas/inmobiliario/2026/05/11/blackstone-refinanciacion.html",
    notes: "LTV objetivo 55% · 38 activos · ES + IT + PT.",
  },
  {
    id: "tx-004",
    newsId: "mn-004",
    newsTitle: "Accor and CDC create €500M JV for European luxury repositioning",
    sourceSlug: "hospitalitynet",
    category: "joint_venture",
    assetName: "Accor × CDC Luxury Repositioning JV",
    country: "FR",
    city: "Paris · Barcelona",
    market: "Europe · Luxury",
    rooms: null,
    priceEur: 500_000_000,
    pricePerKeyEur: null,
    capRate: null,
    closedAt: null,
    announcedAt: "2026-05-10",
    buyer: null,
    seller: null,
    operator: "Accor (Sofitel)",
    brand: "Sofitel",
    advisorBuy: null,
    advisorSell: null,
    sourceUrl: "https://www.hospitalitynet.org/news/4140087-accor-cdc-jv.html",
    notes: "Seed portfolio: 3 Paris + 1 Barcelona.",
  },
];

// ── Extracted projects ──────────────────────────────────────────────────────

export const MOCK_EXTRACTED_PROJECTS: ExtractedProject[] = [
  {
    id: "pr-001",
    newsId: "mn-003",
    newsTitle: "Marriott to open 28 new EDITION-branded hotels in EMEA by 2028",
    sourceSlug: "skift-hospitality",
    category: "pipeline_announcement",
    projectName: "Marriott EDITION EMEA Pipeline · 28 properties",
    country: null,
    city: "Madrid · Lisbon · Athens · …",
    market: "EMEA",
    rooms: null,
    estimatedOpening: "2027-01",
    developer: null,
    operator: "Marriott International",
    brand: "EDITION",
    capexEur: null,
    sourceUrl: "https://skift.com/2026/05/11/marriott-edition-emea-pipeline/",
    notes: "+175% EMEA EDITION footprint.",
  },
  {
    id: "pr-002",
    newsId: "mn-008",
    newsTitle: "Six Senses to debut in Mallorca with 120-key luxury resort opening 2027",
    sourceSlug: "skift-hospitality",
    category: "development",
    projectName: "Six Senses Mallorca · Cap de Formentor",
    country: "ES",
    city: "Cap de Formentor",
    market: "Mallorca",
    rooms: 120,
    estimatedOpening: "2027-09",
    developer: "Inversiones Mallorquinas",
    operator: "Six Senses (IHG)",
    brand: "Six Senses",
    capexEur: 185_000_000,
    sourceUrl: "https://skift.com/2026/05/07/six-senses-mallorca-formentor/",
    notes: "First Six Senses in Spain.",
  },
];

// ── Aggregates ──────────────────────────────────────────────────────────────

export const MOCK_CATEGORY_BREAKDOWN: CategoryBreakdownRow[] = [
  { category: "acquisition",           count: 9,  share: 19.6 },
  { category: "sale",                  count: 3,  share: 6.5  },
  { category: "joint_venture",         count: 2,  share: 4.3  },
  { category: "development",           count: 8,  share: 17.4 },
  { category: "pipeline_announcement", count: 7,  share: 15.2 },
  { category: "refinancing",           count: 4,  share: 8.7  },
  { category: "operator_change",       count: 3,  share: 6.5  },
  { category: "rebranding",            count: 4,  share: 8.7  },
  { category: "investment",            count: 3,  share: 6.5  },
  { category: "distress",              count: 2,  share: 4.3  },
  { category: "flex_living",           count: 1,  share: 2.2  },
];

export const MOCK_ENTITY_MENTIONS: EntityMentionsRow[] = [
  { kind: "investor", name: "Blackstone",         mentions7d: 11, role: "investor", lastSeenAt: "2026-05-12T08:14:00Z", trend: "+4" },
  { kind: "investor", name: "Brookfield",         mentions7d: 7,  role: "buyer",    lastSeenAt: "2026-05-12T08:14:00Z", trend: "+5" },
  { kind: "investor", name: "KKR",                mentions7d: 6,  role: "investor", lastSeenAt: "2026-05-08T13:18:00Z", trend: "+2" },
  { kind: "investor", name: "Stoneweg",           mentions7d: 4,  role: "buyer",    lastSeenAt: "2026-05-08T16:30:00Z", trend: "+3" },
  { kind: "operator", name: "Marriott",           mentions7d: 9,  role: "operator", lastSeenAt: "2026-05-11T11:03:00Z", trend: "+1" },
  { kind: "operator", name: "Accor",              mentions7d: 8,  role: "operator", lastSeenAt: "2026-05-10T09:40:00Z", trend: "stable" },
  { kind: "operator", name: "Meliá",              mentions7d: 7,  role: "seller",   lastSeenAt: "2026-05-08T16:30:00Z", trend: "+2" },
  { kind: "operator", name: "Six Senses (IHG)",   mentions7d: 4,  role: "operator", lastSeenAt: "2026-05-07T10:45:00Z", trend: "+4" },
  { kind: "operator", name: "Iberostar",          mentions7d: 5,  role: "operator", lastSeenAt: "2026-05-12T08:14:00Z", trend: "+5" },
];

export const MOCK_SOURCE_COVERAGE: SourceCoverageRow[] = [
  { sourceSlug: "hosteltur",          sourceName: "Hosteltur",          region: "ES",     articles7d: 0,   articlesToday: 0,  signal: "warn",    lastRunAt: null,                       statusLabel: "Awaiting Credentials" },
  { sourceSlug: "alimarket",          sourceName: "Alimarket",          region: "ES",     articles7d: 0,   articlesToday: 0,  signal: "neutral", lastRunAt: null,                       statusLabel: "Not Configured" },
  { sourceSlug: "expansion",          sourceName: "Expansión",          region: "ES",     articles7d: 61,  articlesToday: 8,  signal: "ok",      lastRunAt: "2026-05-12T06:48:00Z",     statusLabel: "Operational" },
  { sourceSlug: "hospitalitynet",     sourceName: "HospitalityNet",     region: "EU",     articles7d: 132, articlesToday: 18, signal: "ok",      lastRunAt: "2026-05-12T06:48:00Z",     statusLabel: "Operational" },
  { sourceSlug: "skift-hospitality",  sourceName: "Skift Hospitality",  region: "GLOBAL", articles7d: 94,  articlesToday: 12, signal: "ok",      lastRunAt: "2026-05-12T06:48:00Z",     statusLabel: "Operational" },
  { sourceSlug: "hvs",                sourceName: "HVS",                region: "GLOBAL", articles7d: 22,  articlesToday: 3,  signal: "ok",      lastRunAt: "2026-05-12T06:48:00Z",     statusLabel: "Operational" },
  { sourceSlug: "reuters-hospitality",sourceName: "Reuters Hospitality",region: "GLOBAL", articles7d: 28,  articlesToday: 4,  signal: "ok",      lastRunAt: "2026-05-12T06:48:00Z",     statusLabel: "Operational" },
];

export const MOCK_RELEVANCE_ALERTS: RelevanceAlert[] = [
  {
    id: "ra-001",
    newsId: "mn-001",
    title: "Brookfield acquires 12-property portfolio from Banco Santander for €820M",
    sourceSlug: "hospitalitynet",
    category: "acquisition",
    band: "critical",
    publishedAt: "2026-05-12T08:14:00Z",
    reason: "Portfolio-scale ES acquisition · €383k/key · institutional-grade buyer",
    url: "https://www.hospitalitynet.org/news/4140123-brookfield-portfolio-spain.html",
  },
  {
    id: "ra-002",
    newsId: "mn-002",
    title: "Blackstone refinancia 1.200 millones en cartera hotelera europea con Goldman Sachs",
    sourceSlug: "expansion",
    category: "refinancing",
    band: "critical",
    publishedAt: "2026-05-11T15:22:00Z",
    reason: "€1.2B refinancing across 38 European assets · benchmark print",
    url: "https://www.expansion.com/empresas/inmobiliario/2026/05/11/blackstone-refinanciacion.html",
  },
  {
    id: "ra-003",
    newsId: "mn-006",
    title: "Meliá vende Princesa Plaza Madrid a Stoneweg por €145M",
    sourceSlug: "expansion",
    category: "sale",
    band: "critical",
    publishedAt: "2026-05-08T16:30:00Z",
    reason: "Madrid CBD single-asset · €357k/key · sale-and-manage-back",
    url: "https://www.expansion.com/empresas/turismo/2026/05/08/melia-princesa-stoneweg.html",
  },
  {
    id: "ra-004",
    newsId: "mn-007",
    title: "KKR-backed Mint House files for restructuring · flex-living conversion",
    sourceSlug: "reuters-hospitality",
    category: "distress",
    band: "high",
    publishedAt: "2026-05-08T13:18:00Z",
    reason: "Distress watchlist · Spanish flex-living conversion · 4 ES assets",
    url: "https://www.reuters.com/business/lifestyle/mint-house-restructuring-2026-05-08/",
  },
];

// ── Top-level bundle ────────────────────────────────────────────────────────

export const MOCK_TERMINAL_DATA: IntelligenceTerminalData = {
  volumeKpis: MOCK_VOLUME_KPIS,
  recentNews: MOCK_RECENT_NEWS,
  extractedDeals: MOCK_EXTRACTED_DEALS,
  extractedProjects: MOCK_EXTRACTED_PROJECTS,
  categoryBreakdown: MOCK_CATEGORY_BREAKDOWN,
  entityMentions: MOCK_ENTITY_MENTIONS,
  sourceCoverage: MOCK_SOURCE_COVERAGE,
  relevanceAlerts: MOCK_RELEVANCE_ALERTS,
};
