export function MethodologicalNote() {
  return (
    <div className="p-8 border-t border-slate-200 bg-white/95 print:p-3 print:bg-white">
      <p className="text-[11px] leading-relaxed text-slate-500 font-medium border-l-4 border-emerald-500 pl-4 print:text-[8px] print:leading-snug">
        <strong className="text-forest-900 block mb-1">Methodological Note:</strong>
        Valoración estimada con modelo dinámico v4.1 basado en parámetros operativos del activo y
        transacciones hoteleras del submercado. Calculations assume standarized accounting USALI.
        El Cap Rate se calcula sobre EBITDA after replacement. This valuation report is generated by
        HotelVALORA Institutional algorithms based on market data up to August 2024. This is an
        automated assessment with actual market data and does not substitute a formal RICS-certified
        appraisal.
      </p>
    </div>
  );
}
