-- Deprecated standalone schema file — superseded by the migrations
-- directory on 2026-05-11.
--
-- The canonical schema lives in numbered migration files:
--
--   docs/database/migrations/0001_initial_schema.sql    (30 tables, v1)
--
-- See docs/database/README.md for the ER summary, ready-vs-placeholder
-- map and apply instructions.
