/**
 * Supabase Database — hand-rolled type surface.
 *
 * Generated by hand from `docs/database/migrations/0001_initial_schema.sql`
 * because the Supabase CLI requires a personal access token we haven't
 * provisioned yet. Replace this file the moment the access token lands:
 *
 *   pnpm dlx supabase gen types typescript \
 *     --project-id twebgqutuqgonabvhzjk    \
 *     --schema public                       \
 *     > apps/web/src/lib/supabase/types.ts
 *
 * Shape contract:
 *   - `Row`     : exactly what `.select()` returns for the table
 *   - `Insert`  : payload for `.insert()` (nullable defaults are optional)
 *   - `Update`  : payload for `.update()` (every column optional)
 *
 * jsonb columns are typed `Json` for flexibility — narrow them in
 * application code by casting through a typed helper.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ─── Enum values mirror migration 0001 ────────────────────────────────────
export type UserTier = "free" | "pro" | "premium" | "team" | "enterprise";
export type UserRoleEnum = "user" | "admin" | "owner";
export type OrgRole = "owner" | "admin" | "member" | "viewer";
export type OAuthProviderEnum = "google" | "linkedin" | "apple" | "microsoft";
export type ReportVisibility = "private" | "team" | "public" | "top-promote";
export type ReportTypeBadge = "Premium" | "PRO" | "Public" | "Private";
export type ReportStatus = "draft" | "published" | "archived";
export type ReportRoleEnum = "Principal" | "Broker" | "Lender" | "Developer";
export type ReportObjective =
  | "For Sale"
  | "Rent HMA"
  | "Lending"
  | "Develop"
  | "CoInvest";
export type SharePermission = "view" | "comment" | "edit";
export type LeadStatus =
  | "new"
  | "qualified"
  | "contacted"
  | "proposal"
  | "closed_won"
  | "closed_lost";
export type PdfStatus = "queued" | "generating" | "ready" | "failed";
export type ExcelStatus =
  | "queued"
  | "parsing"
  | "staged"
  | "applied"
  | "failed";
export type SubscriptionStatus =
  | "active"
  | "trialing"
  | "past_due"
  | "canceled"
  | "incomplete";
export type NotificationKind =
  | "tour_request"
  | "promotion_expiring"
  | "comment"
  | "share"
  | "system";

// ─── Row shapes ───────────────────────────────────────────────────────────

interface UsersRow {
  id: string;
  email: string;
  tier: UserTier;
  role: UserRoleEnum;
  current_organization_id: string | null;
  stripe_customer_id: string | null;
  created_at: string;
  updated_at: string;
}

interface ProfilesRow {
  user_id: string;
  full_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  phone: string | null;
  locale: string;
  timezone: string;
  created_at: string;
  updated_at: string;
}

interface OrganizationsRow {
  id: string;
  name: string;
  slug: string;
  owner_id: string;
  plan: UserTier;
  logo_url: string | null;
  created_at: string;
  updated_at: string;
}

interface UserRolesRow {
  user_id: string;
  organization_id: string;
  role: OrgRole;
  invited_by: string | null;
  joined_at: string;
}

interface SessionsRow {
  id: string;
  user_id: string;
  ip: string | null;
  user_agent: string | null;
  signed_in_at: string;
  signed_out_at: string | null;
  last_seen_at: string;
}

interface OAuthAccountsRow {
  id: string;
  user_id: string;
  provider: OAuthProviderEnum;
  provider_account_id: string;
  linked_email: string | null;
  linked_at: string;
}

interface ValuationsRow {
  id: string;
  owner_id: string;
  organization_id: string | null;
  hotel_name: string;
  classification: string | null;
  star_rating: number | null;
  rooms: number | null;
  city: string;
  country: string;
  address: string | null;
  zip: string | null;
  sub_market: string | null;
  location_score: number | null;
  lat: number | null;
  lng: number | null;
  open_year: number | null;
  class_label: string | null;
  owner_label: string | null;
  role: ReportRoleEnum | null;
  objective: ReportObjective | null;
  visibility: ReportVisibility;
  report_type: ReportTypeBadge;
  financials: Json;
  amenities: Json;
  indicators: Json;
  contact_info: Json | null;
  status: ReportStatus;
  reference_code: string | null;
  created_at: string;
  updated_at: string;
}

interface SavedReportsRow {
  id: string;
  valuation_id: string;
  version: number;
  snapshot: Json;
  pdf_path: string | null;
  created_by: string;
  created_at: string;
}

interface FavoriteReportsRow {
  user_id: string;
  valuation_id: string;
  created_at: string;
}

interface TopPromoteReportsRow {
  valuation_id: string;
  promoted_by: string;
  promoted_at: string;
  promoted_until: string;
  boost_score: number | null;
  sponsor_priority: number;
  featured_region: string | null;
  impressions: number;
  clicks: number;
  is_active: boolean;
}

interface ReportVisibilityRow {
  id: string;
  valuation_id: string;
  changed_by: string;
  previous_visibility: ReportVisibility | null;
  new_visibility: ReportVisibility;
  reason: string | null;
  changed_at: string;
}

interface ReportSharesRow {
  id: string;
  valuation_id: string;
  shared_by: string;
  shared_with: string | null;
  permission: SharePermission;
  token: string | null;
  expires_at: string | null;
  created_at: string;
}

interface InvestmentRequirementsRow {
  user_id: string;
  asset: Json;
  facilities: Json;
  coverage: Json;
  growth: Json;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

interface MarketPreferencesRow {
  id: string;
  user_id: string;
  country_code: string | null;
  city: string | null;
  sub_market: string | null;
  revpar_scenario: "DOWN" | "BASE" | "UP" | null;
  target: Json | null;
  created_at: string;
}

interface ValuationPreferencesRow {
  user_id: string;
  site: Json;
  exit: Json;
  rent: Json;
  finance: Json;
  pl_forecast: Json;
  updated_at: string;
}

interface RevparScenariosRow {
  id: string;
  user_id: string;
  name: string;
  scenario: "DOWN" | "BASE" | "UP" | "CUSTOM" | null;
  revpar_eur: number | null;
  adr_eur: number | null;
  occupancy: number | null;
  created_at: string;
}

interface HotelFiltersRow {
  id: string;
  user_id: string;
  name: string;
  criteria: Json;
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

interface CompaniesRow {
  id: string;
  owner_id: string;
  name: string;
  website: string | null;
  industry: string | null;
  size: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

interface ContactsRow {
  id: string;
  owner_id: string;
  company_id: string | null;
  full_name: string;
  email: string | null;
  phone: string | null;
  position: string | null;
  source: string | null;
  created_at: string;
  updated_at: string;
}

interface LeadsRow {
  id: string;
  owner_id: string;
  contact_id: string;
  status: LeadStatus;
  source: string | null;
  estimated_value_eur: number | null;
  expected_close_date: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

interface NotesRow {
  id: string;
  owner_id: string;
  entity_type:
    | "contact"
    | "lead"
    | "company"
    | "valuation"
    | "organization";
  entity_id: string;
  body: string;
  created_at: string;
  updated_at: string;
}

interface ActivityLogRow {
  id: string;
  actor_id: string | null;
  entity_type: string;
  entity_id: string;
  action: string;
  metadata: Json | null;
  occurred_at: string;
}

interface ReportFilesRow {
  id: string;
  valuation_id: string;
  uploaded_by: string;
  bucket: string;
  storage_path: string;
  file_name: string;
  mime_type: string | null;
  size_bytes: number | null;
  created_at: string;
}

interface GeneratedPdfsRow {
  id: string;
  saved_report_id: string | null;
  requested_by: string;
  bucket: string;
  storage_path: string | null;
  status: PdfStatus;
  error_message: string | null;
  requested_at: string;
  completed_at: string | null;
}

interface UploadedExcelsRow {
  id: string;
  uploaded_by: string;
  bucket: string;
  storage_path: string;
  file_name: string;
  size_bytes: number | null;
  status: ExcelStatus;
  parsed_summary: Json | null;
  error_message: string | null;
  uploaded_at: string;
  processed_at: string | null;
}

interface RendersRow {
  id: string;
  valuation_id: string | null;
  requested_by: string;
  bucket: string;
  storage_path: string | null;
  prompt: string | null;
  provider: string | null;
  model: string | null;
  cost_usd: number | null;
  created_at: string;
}

interface AvatarsRow {
  id: string;
  user_id: string;
  bucket: string;
  storage_path: string;
  is_current: boolean;
  created_at: string;
}

interface AuditLogsRow {
  id: string;
  actor_id: string | null;
  event_type: string;
  entity_type: string | null;
  entity_id: string | null;
  before_state: Json | null;
  after_state: Json | null;
  metadata: Json | null;
  reversible: boolean;
  reverted_at: string | null;
  reverted_by: string | null;
  created_at: string;
}

interface NotificationsRow {
  id: string;
  user_id: string;
  kind: NotificationKind;
  title: string;
  body: string | null;
  payload: Json | null;
  read_at: string | null;
  created_at: string;
}

interface FeatureFlagsRow {
  id: string;
  flag: string;
  user_id: string | null;
  organization_id: string | null;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

interface SubscriptionsRow {
  id: string;
  user_id: string;
  organization_id: string | null;
  stripe_customer_id: string;
  stripe_subscription_id: string | null;
  tier: UserTier;
  status: SubscriptionStatus;
  current_period_start: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  created_at: string;
  updated_at: string;
}

interface PaymentEventsRow {
  id: string;
  stripe_event_id: string;
  event_type: string;
  payload: Json;
  related_user: string | null;
  related_subscription: string | null;
  processed: boolean;
  received_at: string;
}

// ─── Helper — derive Insert / Update from Row ────────────────────────────
// `Insert<T>` keeps the columns we typically supply on create. Columns
// with DB defaults (`created_at`, generated UUIDs, etc.) are made
// optional via `Partial`. The Supabase JS client accepts this shape.

type Optional<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

type InsertOf<T> = Partial<T>;
type UpdateOf<T> = Partial<T>;

// ─── Database type — what `createClient<Database>()` consumes ─────────────

export interface Database {
  public: {
    Tables: {
      users: { Row: UsersRow; Insert: InsertOf<UsersRow>; Update: UpdateOf<UsersRow>; Relationships: [] };
      profiles: { Row: ProfilesRow; Insert: InsertOf<ProfilesRow>; Update: UpdateOf<ProfilesRow>; Relationships: [] };
      organizations: { Row: OrganizationsRow; Insert: InsertOf<OrganizationsRow>; Update: UpdateOf<OrganizationsRow>; Relationships: [] };
      user_roles: { Row: UserRolesRow; Insert: InsertOf<UserRolesRow>; Update: UpdateOf<UserRolesRow>; Relationships: [] };
      sessions: { Row: SessionsRow; Insert: InsertOf<SessionsRow>; Update: UpdateOf<SessionsRow>; Relationships: [] };
      oauth_accounts: { Row: OAuthAccountsRow; Insert: InsertOf<OAuthAccountsRow>; Update: UpdateOf<OAuthAccountsRow>; Relationships: [] };

      valuations: { Row: ValuationsRow; Insert: InsertOf<ValuationsRow>; Update: UpdateOf<ValuationsRow>; Relationships: [] };
      saved_reports: { Row: SavedReportsRow; Insert: InsertOf<SavedReportsRow>; Update: UpdateOf<SavedReportsRow>; Relationships: [] };
      favorite_reports: { Row: FavoriteReportsRow; Insert: InsertOf<FavoriteReportsRow>; Update: UpdateOf<FavoriteReportsRow>; Relationships: [] };
      top_promote_reports: { Row: TopPromoteReportsRow; Insert: InsertOf<TopPromoteReportsRow>; Update: UpdateOf<TopPromoteReportsRow>; Relationships: [] };
      report_visibility: { Row: ReportVisibilityRow; Insert: InsertOf<ReportVisibilityRow>; Update: UpdateOf<ReportVisibilityRow>; Relationships: [] };
      report_shares: { Row: ReportSharesRow; Insert: InsertOf<ReportSharesRow>; Update: UpdateOf<ReportSharesRow>; Relationships: [] };

      investment_requirements: { Row: InvestmentRequirementsRow; Insert: InsertOf<InvestmentRequirementsRow>; Update: UpdateOf<InvestmentRequirementsRow>; Relationships: [] };
      market_preferences: { Row: MarketPreferencesRow; Insert: InsertOf<MarketPreferencesRow>; Update: UpdateOf<MarketPreferencesRow>; Relationships: [] };
      valuation_preferences: { Row: ValuationPreferencesRow; Insert: InsertOf<ValuationPreferencesRow>; Update: UpdateOf<ValuationPreferencesRow>; Relationships: [] };
      revpar_scenarios: { Row: RevparScenariosRow; Insert: InsertOf<RevparScenariosRow>; Update: UpdateOf<RevparScenariosRow>; Relationships: [] };
      hotel_filters: { Row: HotelFiltersRow; Insert: InsertOf<HotelFiltersRow>; Update: UpdateOf<HotelFiltersRow>; Relationships: [] };

      companies: { Row: CompaniesRow; Insert: InsertOf<CompaniesRow>; Update: UpdateOf<CompaniesRow>; Relationships: [] };
      contacts: { Row: ContactsRow; Insert: InsertOf<ContactsRow>; Update: UpdateOf<ContactsRow>; Relationships: [] };
      leads: { Row: LeadsRow; Insert: InsertOf<LeadsRow>; Update: UpdateOf<LeadsRow>; Relationships: [] };
      notes: { Row: NotesRow; Insert: InsertOf<NotesRow>; Update: UpdateOf<NotesRow>; Relationships: [] };
      activity_log: { Row: ActivityLogRow; Insert: InsertOf<ActivityLogRow>; Update: UpdateOf<ActivityLogRow>; Relationships: [] };

      report_files: { Row: ReportFilesRow; Insert: InsertOf<ReportFilesRow>; Update: UpdateOf<ReportFilesRow>; Relationships: [] };
      generated_pdfs: { Row: GeneratedPdfsRow; Insert: InsertOf<GeneratedPdfsRow>; Update: UpdateOf<GeneratedPdfsRow>; Relationships: [] };
      uploaded_excels: { Row: UploadedExcelsRow; Insert: InsertOf<UploadedExcelsRow>; Update: UpdateOf<UploadedExcelsRow>; Relationships: [] };
      renders: { Row: RendersRow; Insert: InsertOf<RendersRow>; Update: UpdateOf<RendersRow>; Relationships: [] };
      avatars: { Row: AvatarsRow; Insert: InsertOf<AvatarsRow>; Update: UpdateOf<AvatarsRow>; Relationships: [] };

      audit_logs: { Row: AuditLogsRow; Insert: InsertOf<AuditLogsRow>; Update: UpdateOf<AuditLogsRow>; Relationships: [] };
      notifications: { Row: NotificationsRow; Insert: InsertOf<NotificationsRow>; Update: UpdateOf<NotificationsRow>; Relationships: [] };
      feature_flags: { Row: FeatureFlagsRow; Insert: InsertOf<FeatureFlagsRow>; Update: UpdateOf<FeatureFlagsRow>; Relationships: [] };
      subscriptions: { Row: SubscriptionsRow; Insert: InsertOf<SubscriptionsRow>; Update: UpdateOf<SubscriptionsRow>; Relationships: [] };
      payment_events: { Row: PaymentEventsRow; Insert: InsertOf<PaymentEventsRow>; Update: UpdateOf<PaymentEventsRow>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_tier: UserTier;
      user_role: UserRoleEnum;
      org_role: OrgRole;
      oauth_provider: OAuthProviderEnum;
      report_visibility_t: ReportVisibility;
      report_type_badge: ReportTypeBadge;
      report_status: ReportStatus;
      report_role: ReportRoleEnum;
      report_objective: ReportObjective;
      share_permission: SharePermission;
      lead_status: LeadStatus;
      pdf_status: PdfStatus;
      excel_status: ExcelStatus;
      subscription_status: SubscriptionStatus;
      notification_kind: NotificationKind;
    };
  };
}
