import type { CompTransaction } from "../types";

/**
 * Seeded comparable transactions · MVP stub.
 *
 * Block 6 ships with curated Spanish hotel comps (Madrid + Barcelona +
 * Marbella) covering 2023-2026 so Section 6's Dynamic Cap Rate Card has
 * institutional-grade evidence to render. Block 7 will swap this for a
 * Supabase-backed `hotel_transactions` table queried via the
 * Intelligence Layer.
 *
 * All values are plausible and representative · NOT confidential real
 * transactions. Used here purely for engine validation + UI demo until
 * the live intelligence layer lands.
 */
export const SEEDED_HOTEL_COMPS: CompTransaction[] = [
  // Madrid Centro · 4-5* · institutional core
  {
    transaction_id: "MAD-2024-Q3-001",
    hotel_name: "Hotel Centro Reference 4* (anon)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 240,
    state: "renovated",
    transaction_date: "2024-08-15",
    cap_rate_pct: 6.20,
    price_total_eur: 78_500_000,
    price_per_key_eur: 327_083,
    source: "Cushman & Wakefield · 2024 H2 Hotel Investment Review",
  },
  {
    transaction_id: "MAD-2024-Q1-002",
    hotel_name: "Hotel Centro Reference 4* (anon, II)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 198,
    state: "renovated",
    transaction_date: "2024-03-22",
    cap_rate_pct: 6.35,
    price_total_eur: 64_000_000,
    price_per_key_eur: 323_232,
    source: "JLL Hotels & Hospitality · 2024 H1 Madrid Market Report",
  },
  {
    transaction_id: "MAD-2023-Q4-003",
    hotel_name: "Hotel Salamanca 5* (anon)",
    market: "Madrid",
    submarket: "Salamanca",
    category: "5star",
    rooms: 145,
    state: "renovated",
    transaction_date: "2023-11-30",
    cap_rate_pct: 5.40,
    price_total_eur: 92_000_000,
    price_per_key_eur: 634_483,
    source: "CBRE Hotels · 2023 Year-End Iberia Report",
  },
  {
    transaction_id: "MAD-2025-Q1-004",
    hotel_name: "Hotel Centro 4* (anon, III)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 312,
    state: "new",
    transaction_date: "2025-02-10",
    cap_rate_pct: 5.95,
    price_total_eur: 105_000_000,
    price_per_key_eur: 336_538,
    source: "Colliers · Madrid Hotel Investment Watch Q1 2025",
  },
  {
    transaction_id: "MAD-2024-Q2-005",
    hotel_name: "Hotel Chamberi 3* (anon)",
    market: "Madrid",
    submarket: "Chamberi",
    category: "3star",
    rooms: 92,
    state: "needs_work",
    transaction_date: "2024-05-18",
    cap_rate_pct: 7.15,
    price_total_eur: 19_500_000,
    price_per_key_eur: 211_957,
    source: "Savills Spain · 2024 H1 Independent Hotel Market",
  },
  {
    transaction_id: "MAD-2025-Q2-006",
    hotel_name: "Hotel Centro 4* (anon, IV)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 256,
    state: "renovated",
    transaction_date: "2025-06-05",
    cap_rate_pct: 6.10,
    price_total_eur: 83_000_000,
    price_per_key_eur: 324_219,
    source: "HVS · Madrid Hotel Pulse Q2 2025",
  },
  {
    transaction_id: "MAD-2023-Q2-007",
    hotel_name: "Hotel Centro 4* (anon, V)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 180,
    state: "renovated",
    transaction_date: "2023-04-28",
    cap_rate_pct: 6.55,
    price_total_eur: 56_000_000,
    price_per_key_eur: 311_111,
    source: "CBRE Hotels · 2023 H1 Iberia Hotel Investment",
  },
  {
    transaction_id: "MAD-2025-Q4-008",
    hotel_name: "Hotel Salamanca 5* (anon, II)",
    market: "Madrid",
    submarket: "Salamanca",
    category: "5star",
    rooms: 110,
    state: "renovated",
    transaction_date: "2025-10-12",
    cap_rate_pct: 5.25,
    price_total_eur: 78_000_000,
    price_per_key_eur: 709_091,
    source: "Cushman & Wakefield · 2025 H2 Luxury Hotel Trends",
  },
  {
    transaction_id: "MAD-2026-Q1-009",
    hotel_name: "Hotel Centro 4* (anon, VI)",
    market: "Madrid",
    submarket: "Madrid Centro",
    category: "4star",
    rooms: 220,
    state: "renovated",
    transaction_date: "2026-02-20",
    cap_rate_pct: 6.30,
    price_total_eur: 72_500_000,
    price_per_key_eur: 329_545,
    source: "JLL · 2026 Q1 Madrid Hotel Investment",
  },

  // Barcelona · for broader market reference
  {
    transaction_id: "BCN-2024-Q4-010",
    hotel_name: "Hotel Eixample 4* (anon)",
    market: "Barcelona",
    submarket: "Eixample",
    category: "4star",
    rooms: 195,
    state: "renovated",
    transaction_date: "2024-11-08",
    cap_rate_pct: 6.40,
    price_total_eur: 68_000_000,
    price_per_key_eur: 348_718,
    source: "CBRE Hotels · 2024 H2 Barcelona Report",
  },
  {
    transaction_id: "BCN-2025-Q2-011",
    hotel_name: "Hotel Gothic 4* (anon)",
    market: "Barcelona",
    submarket: "Gothic Quarter",
    category: "4star",
    rooms: 142,
    state: "new",
    transaction_date: "2025-04-15",
    cap_rate_pct: 5.85,
    price_total_eur: 58_000_000,
    price_per_key_eur: 408_451,
    source: "Cushman & Wakefield · 2025 H1 Iberia Report",
  },

  // Marbella · resort reference
  {
    transaction_id: "MRB-2024-Q3-012",
    hotel_name: "Resort Marbella 5* (anon)",
    market: "Marbella",
    submarket: "Marbella Centro",
    category: "5star",
    rooms: 320,
    state: "renovated",
    transaction_date: "2024-09-25",
    cap_rate_pct: 6.10,
    price_total_eur: 195_000_000,
    price_per_key_eur: 609_375,
    source: "Christie & Co · 2024 Resort Hotel Report",
  },
];
